myblog/myblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from blogs import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog_form/$', views.blog_form),
    url(r'^blog_list/$', views.blog_del),
    url(r'^blog_view/$', views.blog_view),
    url(r'^blog_edit/$', views.blog_edit),
]

myblog/blogs/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(u'标题', max_length=50)
    author = models.CharField(u'旅游景点', max_length=10)
    content = models.CharField(u'正文', max_length=2000)
    post_date = models.DateTimeField(u'发布时间', auto_now_add=True)


    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-post_date']

myblog/blogs/forms.py
from django import forms


class BlogForm(forms.Form):
    title = forms.CharField(label='标题')
    author = forms.CharField(label='作者')
    content = forms.CharField(label='正文', widget=forms.Textarea)

myblog/blogs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from blogs.models import Blog


def blog_form(request):
    state = None
    if request.method == 'POST':
        if Blog.objects.all().exists():
            blog_last = Blog.objects.all().order_by('-id')[0]
            Blog.id = int(blog_last.id) + 1
        else:
            Blog.id = 0
        new_blog = Blog(
            id=Blog.id,
            title=request.POST.get('title', ''),
            author=request.POST.get('author', ''),
            content=request.POST.get('content', ''),
        )
        new_blog.save()

        state = 'success'

    con = {
        'state': state,
    }
    return render(request, 'yemian/blog_form.html', con)


def blog_del(request):
    blog_list = Blog.objects.all()
    if request.GET.get('operate') == 'delete':
        bid_ = request.GET['id']
        Blog.objects.filter(id=bid_).delete()
    content = {
        'blog_list': blog_list,
    }

    return render(request, 'yemian/blog_list.html', content)


def blog_view(request):
    errors = []
    if 'id' in request.GET:
        bid_ = request.GET['id']
        blog = Blog.objects.get(id=bid_)
        return render(request, 'yemian/blog_view.html',{'blog':blog})
    else:
        errors.append("参数异常从而发生了未知错误")
        return render(request, 'yemian/blog_list.html',{'errors':errors})


def blog_edit(request):
    content = dict()
    if request.method == 'POST':
        bid_ = request.POST.get('id')
        blog = Blog.objects.filter(id__iexact=bid_)

        if request.POST.get('new_title'):
            blog.update(title=request.POST.get('new_title'))
        if request.POST.get('new_author'):
            blog.update(author=request.POST.get('new_author'))
        if request.POST.get('new_content'):
            blog.update(content=request.POST.get('new_content'))
        blog_info = Blog.objects.get(id=bid_)
        content = {
            'blog': blog_info,
        }
    elif request.method == 'GET':
        bid_ = request.GET.get('id')
        blog = Blog.objects.get(id=bid_)
        content = {
            'blog': blog,
        }

    return render(request, 'yemian/blog_edit.html', content)

myblog/templates/yemian/blog_edit.html
{% load staticfiles %}
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>编辑博客</title>
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- 引入 Bootstrap -->
		<link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link href="css/main.css"rel="stylesheet"type="text/css"/>
	</head>

	<body style="background-image:url({% static 'img/blogback.jpg' %});background-position:center; background-repeat:no-repeat;background-attachment: fixed;font-family: 方正清刻本悦宋简体;font-size: large">
        <br>
        <br>
    <form method="POST">
        {% csrf_token %}
		<div class="container">
			<div class="row clearfix">
				<div class="col-md-1 column">
				</div>
				<div class="col-md-10 column">
					<form method="post">
                        <a href="/blog_list">返回博客表单>></a><p/>
                        <div>
                            <input style="display: none" class="form-control" id="id_id" required name="id" value="{{ blog.id }}">
                        </div>
						<div class="form-group">
							 <label for="exampleInputEmail1">博客题目（づ￣3￣）づ╭❤～：<br></label>
							 <input type="text" style="width:250px; height:35px;background:rgba(133, 133, 133, 0.1);"  class="form-control" id="id_title" required name="new_title" autofocus value="{{ blog.title }}">
						</div>
						<div class="form-group">
							 <label for="exampleInputPassword1">旅游景点（づ￣3￣）づ╭❤～:<br></label>
							 <input type="text" style="width:250px; height:35px;background:rgba(133, 133, 133, 0.1);" class="form-control" id="id_author" required name="new_author" value="{{ blog.author }}">
						</div>
                        <div>
							<label for="id_content">正文（づ￣3￣）づ╭❤～:<br></label>
							<textarea type="text" style="width:1000px; height:600px;background:rgba(133, 133, 133, 0.1);" class="form-control" id="id_content" required name="new_content">{{ blog.content }}</textarea>
						</div><br>
                        <input type="submit" style="width:70px; height:30px;" class="btn btn-default" value="保存"><br><br>
					<a href="/blog_list">返回博客表单>></a><p/>
                    </form>
				</div>
				<div class="col-md-1 column">
				</div>
			</div>
		</div>
    </form>
</body>
</html>

myblog/templates/yemian/blog_form.html
{% load staticfiles %}
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>博客编辑</title>
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- 引入 Bootstrap -->
		<link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link href="css/main.css"rel="stylesheet"type="text/css"/>
	</head>

	<body style="background-image:url({% static 'img/blogback.jpg' %});background-position:center; background-repeat:no-repeat;background-attachment: fixed;font-family: 方正清刻本悦宋简体;font-size: large">
        <br>
        <br>
		<div class="container">
			<div class="row clearfix">
				<div class="col-md-1 column">
				</div>
				<div class="col-md-10 column">
					<form method="post">
						{% csrf_token %}
                        <a href="/blog_list">返回博客表单>></a><p/>
                        {% if state == 'success' %}
                        <div style="width: 100%;">添加成功，(๑•ᴗ•๑)</div>
                        {% endif %}
						<div class="form-group">
							 <label for="exampleInputEmail1">博客题目（づ￣3￣）づ╭❤～：<br></label>
							 <input type="text" style="width:250px; height:35px;background:rgba(133, 133, 133, 0.1);" class="form-control" id="id_title" required name="title" autofocus>
						</div>
						<div class="form-group">
							 <label for="exampleInputPassword1">旅游景点（づ￣3￣）づ╭❤～:<br></label>
							 <input type="text" style="width:250px; height:35px;background:rgba(133, 133, 133, 0.1);" class="form-control" id="id_author" required name="author">
						</div>
                        <div>
							<label for="id_content">正文（づ￣3￣）づ╭❤～:<br></label>
							<textarea type="text" style="width:1000px; height:700px;background:rgba(133, 133, 133, 0.1);" class="form-control" id="id_content" required name="content"></textarea>
						</div><br>
                        <input type="submit" style="width:70px; height:30px;background:rgba(133, 133, 133, 0.1);" class="btn btn-default" value="保存"><br><br>
					<a href="/blog_list">返回博客表单>></a><p/>
				</div>
				<div class="col-md-1 column">
				</div>
			</div>
		</div>
	</body>

myblog/templates/yemian/blog_list.html
{% load staticfiles %}
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>{{blog.title}}</title>
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- 引入 Bootstrap -->
		<link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link href="css/main.css"rel="stylesheet"type="text/css"/>
	</head>

    <body style="background-image:url({% static 'img/blogback.jpg' %});background-position:center; background-repeat:no-repeat;background-attachment: fixed;font-family: 方正清刻本悦宋简体;font-size: large">
       <div class="container">
            <div class="row clearfix">
                <div class="col-md-1 column">
                </div>
                <div class="col-md-10 column">
                <br><br><a href="/blog_form">去写博客>></a><p/><br>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>
                                    编号
                                </th>
                                <th>
                                    标题
                                </th>
                                <th>
                                    旅游景点
                                </th>
                                <th>
                                    发布时间
                                </th>
                                <th>
                                    操作
                                </th>
                                {% for blog in blog_list %}
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    {{forloop.counter}}
                                </td>
                                <td>
                                    <a href="/blog_view?id={{blog.id}}">{{blog.title}}</a>
                                </td>
                                <td>
                                    {{blog.author}}
                                </td>
                                <td>
                                    {{blog.post_date | date:"Y-m-d H:i:s"}}
                                </td>
                                <td>
                                    <a href="/blog_edit?id={{blog.id}}&operate=update">修改</a>&nbsp;<a href="/blog_list?id={{ blog.id }}&operate=delete">删除</a></td>
                                </td>
                            </tr>
                        </tbody>
                        {% empty %}
                        <tr><td colspan="4">还没有添加任何博客信息</td></tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="col-md-1 column">
                </div>
            </div>
        </div>
    </body>
</html>

myblog/templates/yemian/blog_view.html
{% load staticfiles %}
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>{{blog.title}}</title>
    <head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<!-- 引入 Bootstrap -->
		<link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link href="css/main.css"rel="stylesheet"type="text/css"/>
	</head>
    <body style="background-image:url({% static 'img/blogback.jpg' %});background-position:center; background-repeat:no-repeat;background-attachment: fixed;font-family: 方正清刻本悦宋简体;font-size: large">
		<div class="container">
            <div class="row clearfix">
                <div class="col-md-1column"></div>
                <div class="col-md-10 column">
                    <div class="page-header">
                        <h1>
                            {{blog.title}} <small>{{blog.post_date | date:'Y-m-d H:i:s'}}</small>
                        </h1>
                    </div>
                    <h4>
                    <b>旅游景点：{{blog.author}}</b>
                    </h4>
                    <p>
                        {{blog.content}}<br>
                    </p>
                    <a href="/blog_list?id={{blog.id}}">返回博客表单</a>
                </div>
                <div class="col-md-1 column"></div>
            </div>
        </div>
    </body>
</html>